package server

import (
	"net/http"
	"path/filepath"
	"strings"
)

// installScriptTemplate uses {{PLACEHOLDER}} tokens replaced via strings.ReplaceAll.
// This avoids any conflict with % in bash syntax.
var installScriptTemplate = `#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
#  OpenFleet — OpAMP Agent Install Script
#  Auto-generated by OpenFleet Dashboard
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config (injected by OpenFleet — reflects your selections in the wizard) ────
OPAMP_ENDPOINT="{{ENDPOINT}}"
OTEL_VERSION="{{OTEL_VERSION}}"
SUPERVISOR_VERSION="{{SUPERVISOR_VERSION}}"
AGENT_LABEL="{{LABEL}}"

INSTALL_DIR="{{INSTALL_DIR}}"
BIN_DIR="{{BIN_DIR}}"
CONF_DIR="{{CONF_DIR}}"
STORAGE_DIR="{{STORAGE_DIR}}"
OTEL_USER="{{OTEL_USER}}"
SERVICE_NAME="{{SERVICE_NAME}}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
err()     { echo -e "${RED}[✗]${NC} $*"; exit 1; }
section() { echo -e "\n${BLUE}━━━ $* ━━━${NC}"; }

# ── Uninstall flag ────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--uninstall" ]]; then
  section "Uninstalling OpenFleet Agent"
  systemctl stop  "$SERVICE_NAME" 2>/dev/null && info "Service stopped."   || warn "Service was not running."
  systemctl disable "$SERVICE_NAME" 2>/dev/null || true
  rm -f /etc/systemd/system/${SERVICE_NAME}.service
  systemctl daemon-reload
  rm -rf "$INSTALL_DIR" "$CONF_DIR" "$STORAGE_DIR"
  userdel -r "$OTEL_USER" 2>/dev/null && info "User '$OTEL_USER' removed." || warn "User not found."
  info "Uninstall complete."
  exit 0
fi

# ── Root check ────────────────────────────────────────────────────────────────
[[ "$EUID" -ne 0 ]] && err "Please run as root (sudo)."

section "OpenFleet Agent Installation"
info "Endpoint : $OPAMP_ENDPOINT"
info "OTel v   : $OTEL_VERSION"
info "Label    : ${AGENT_LABEL:-<none>}"

# ── 1. Connectivity pre-check ─────────────────────────────────────────────────
section "Connectivity Check"
PING_URL=$(echo "$OPAMP_ENDPOINT" | sed 's|^wss://|https://|; s|^ws://|http://|')
HTTP_CODE=$(curl --max-time 10 --silent --output /dev/null \
            --write-out "%{http_code}" "$PING_URL" || echo "000")
if [[ "$HTTP_CODE" =~ ^(200|400|404|101|426)$ ]]; then
  info "Server reachable (HTTP $HTTP_CODE) ✓"
else
  warn "Server returned HTTP $HTTP_CODE — continuing anyway (WebSocket-only endpoints may show this)."
fi

# ── 2. Dependencies ───────────────────────────────────────────────────────────
section "Dependencies"
PKG="curl tar gzip"
if   command -v apt-get &>/dev/null; then apt-get update -qq && apt-get install -y -qq $PKG
elif command -v dnf     &>/dev/null; then dnf  install -y $PKG
elif command -v yum     &>/dev/null; then yum  install -y $PKG
elif command -v pacman  &>/dev/null; then pacman -Sy --noconfirm $PKG
else err "Unsupported package manager. Install curl and tar manually."; fi
info "Dependencies OK"

# ── 3. User & directories ─────────────────────────────────────────────────────
section "Environment"
id -u "$OTEL_USER" &>/dev/null || useradd -r -m -s /bin/false "$OTEL_USER"
mkdir -p "$BIN_DIR" "$CONF_DIR" "$STORAGE_DIR"
chown -R "$OTEL_USER:$OTEL_USER" "$INSTALL_DIR" "$STORAGE_DIR"
info "User '$OTEL_USER' and directories ready"

# ── 4. OTel Contrib Collector ─────────────────────────────────────────────────
section "OTel Contrib Collector v${OTEL_VERSION}"
if [[ -f "$BIN_DIR/otelcol-contrib" ]]; then
  warn "Already installed — skipping download."
else
  ARCH=$(uname -m)
  case $ARCH in x86_64) ARCH=amd64;; aarch64) ARCH=arm64;; armv7l) ARCH=arm;; esac
  URL="https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v${OTEL_VERSION}/otelcol-contrib_${OTEL_VERSION}_linux_${ARCH}.tar.gz"
  curl -fsSL "$URL" -o /tmp/otelcol.tar.gz
  tar -xzf /tmp/otelcol.tar.gz -C "$BIN_DIR" otelcol-contrib
  chmod +x "$BIN_DIR/otelcol-contrib"
  rm /tmp/otelcol.tar.gz
  info "otelcol-contrib installed ✓"
fi

# ── 5. OpAMP Supervisor ───────────────────────────────────────────────────────
section "OpAMP Supervisor"
if [[ ! -f "$BIN_DIR/opamp-supervisor" ]]; then
  info "Downloading official opamp-supervisor binary from OpenTelemetry..."
  ARCH=$(uname -m)
  case $ARCH in x86_64) ARCH=amd64;; aarch64) ARCH=arm64;; armv7l) ARCH=arm;; esac
  URL="https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fopampsupervisor%2Fv${SUPERVISOR_VERSION}/opampsupervisor_${SUPERVISOR_VERSION}_linux_${ARCH}"
  curl -fsSL "$URL" -o "$BIN_DIR/opamp-supervisor"
  chmod +x "$BIN_DIR/opamp-supervisor"
  info "opamp-supervisor downloaded and installed ✓"
fi

# ── 6. Supervisor config ──────────────────────────────────────────────────────
section "Supervisor Configuration"
cat > "$CONF_DIR/supervisor.yaml" <<'YAML'
{{SUPERVISOR_YAML}}
YAML
chown "$OTEL_USER:$OTEL_USER" "$CONF_DIR/supervisor.yaml"
info "Config written to $CONF_DIR/supervisor.yaml"

# ── 7. Systemd service ────────────────────────────────────────────────────────
section "Systemd Service"
cat > /etc/systemd/system/${SERVICE_NAME}.service <<UNIT
[Unit]
Description=OpenFleet OpAMP Supervisor
After=network.target

[Service]
Type=simple
User=${OTEL_USER}
Group=${OTEL_USER}
ExecStart=${BIN_DIR}/opamp-supervisor --config ${CONF_DIR}/supervisor.yaml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl start "$SERVICE_NAME"
info "Service '$SERVICE_NAME' enabled and started"

echo ""
info "Installation complete!"
echo -e "  ${GREEN}Start :${NC}  systemctl start  $SERVICE_NAME"
echo -e "  ${GREEN}Status:${NC}  systemctl status $SERVICE_NAME"
echo -e "  ${GREEN}Logs  :${NC}  journalctl -u $SERVICE_NAME -f"
echo ""
`

var uninstallScriptTemplate = `#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
#  OpenFleet — OpAMP Agent UNINSTALL Script
#  Target Agent UID: {{UID}}
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config (injected by OpenFleet — must match what was used during install) ────
SERVICE_NAME="{{SERVICE_NAME}}"
INSTALL_DIR="{{INSTALL_DIR}}"
CONF_DIR="{{CONF_DIR}}"
STORAGE_DIR="{{STORAGE_DIR}}"
OTEL_USER="{{OTEL_USER}}"
OPENFLEET_URL="{{OPENFLEET_URL}}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info() { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }

[[ "$EUID" -ne 0 ]] && { echo "Please run as root (sudo)."; exit 1; }

echo -e "${RED}Uninstalling OpenFleet agent (UID: {{UID}})...${NC}"

systemctl stop    "$SERVICE_NAME" 2>/dev/null && info "Service stopped."   || warn "Not running."
systemctl disable "$SERVICE_NAME" 2>/dev/null || true
rm -f /etc/systemd/system/${SERVICE_NAME}.service
systemctl daemon-reload

rm -rf "$INSTALL_DIR" "$CONF_DIR" "$STORAGE_DIR"
info "Binaries and config removed."

userdel -r "$OTEL_USER" 2>/dev/null && info "User '$OTEL_USER' removed." || warn "User not found."

# ── Deregister from OpenFleet DB ──────────────────────────────────────────────
if curl -sf -X POST "$OPENFLEET_URL/api/agents/delete?uid={{UID}}" >/dev/null 2>&1; then
  info "Agent deregistered from OpenFleet server."
else
  warn "Could not reach OpenFleet server — remove the agent manually from the dashboard."
fi

info "Uninstall complete. Agent {{UID}} has been removed from this host."
`

func renderScript(tmpl string, replacements map[string]string) string {
	result := tmpl
	for k, v := range replacements {
		result = strings.ReplaceAll(result, k, v)
	}
	return result
}

func sanitizeUID(uid string) string {
	return strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '-' || r == '_' {
			return r
		}
		return -1
	}, uid)
}

func boolParam(q interface{ Get(string) string }, key, defaultVal string) string {
	v := q.Get(key)
	if v == "1" {
		return "true"
	}
	if v == "0" {
		return "false"
	}
	return defaultVal
}

// pathList formats a comma-separated string as a YAML list, e.g. "[/a, /b]"
func pathList(s string) string {
	if s == "" {
		return "[]"
	}
	parts := strings.Split(s, ",")
	result := "["
	for i, p := range parts {
		p = strings.TrimSpace(p)
		if i > 0 {
			result += ", "
		}
		result += p
	}
	return result + "]"
}

// kvLines converts "key=value\nkey2=value2" into YAML key: value lines with indent
func kvLines(raw, indent string) string {
	if raw == "" {
		return ""
	}
	var out []string
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		idx := strings.Index(line, "=")
		if idx < 1 {
			continue
		}
		k := strings.TrimSpace(line[:idx])
		v := strings.TrimSpace(line[idx+1:])
		out = append(out, indent+k+": "+v)
	}
	return strings.Join(out, "\n")
}

// argLines converts "arg\narg2" into YAML list items with indent
func argLines(raw, indent string) string {
	if raw == "" {
		return ""
	}
	var out []string
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		out = append(out, indent+"- "+line)
	}
	return strings.Join(out, "\n")
}

func (srv *server) handleInstallScriptAPI(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	q := r.URL.Query()

	// Basic
	endpoint := q.Get("endpoint")
	if endpoint == "" {
		endpoint = "wss://your-openfleet-server:8080/v1/opamp"
	}
	otelVer := q.Get("otel_version")
	if otelVer == "" {
		otelVer = "0.151.0"
	}
	supVer := q.Get("supervisor_version")
	if supVer == "" {
		supVer = "0.151.0"
	}
	label := q.Get("label")

	// Agent settings
	executable := q.Get("executable")
	if executable == "" {
		executable = "/opt/otelcol/bin/otelcol-contrib"
	}
	runAs := q.Get("run_as")
	if runAs == "" {
		runAs = "otelcol"
	}
	orphanInterval := q.Get("orphan_interval")
	if orphanInterval == "" {
		orphanInterval = "5s"
	}
	bootstrapTimeout := q.Get("bootstrap_timeout")
	if bootstrapTimeout == "" {
		bootstrapTimeout = "3s"
	}
	opampPort := q.Get("opamp_port")
	storageDir := q.Get("storage_dir")
	if storageDir == "" {
		storageDir = "/var/lib/otelcol/supervisor"
	}
	logLevel := q.Get("log_level")
	if logLevel == "" {
		logLevel = "info"
	}
	metricsLevel := q.Get("metrics_level")
	if metricsLevel == "" {
		metricsLevel = "normal"
	}

	// Capabilities
	capRemoteCfg := "true"
	capRestart := boolParam(q, "cap_accepts_restart_command", "true")
	capOpampConn := boolParam(q, "cap_accepts_opamp_connection_settings", "false")
	capEffCfg := boolParam(q, "cap_reports_effective_config", "true")
	capOwnMetrics := boolParam(q, "cap_reports_own_metrics", "true")
	capOwnLogs := boolParam(q, "cap_reports_own_logs", "false")
	capOwnTraces := boolParam(q, "cap_reports_own_traces", "false")
	capHealth := boolParam(q, "cap_reports_health", "true")
	capRemoteSt := "true"
	capComponents := boolParam(q, "cap_reports_available_components", "false")
	capHeartbeat := boolParam(q, "cap_reports_heartbeat", "true")

	// Access dirs
	readAllow := pathList(q.Get("read_allow"))
	readDeny := pathList(q.Get("read_deny"))
	writeAllow := pathList(q.Get("write_allow"))

	// Args & env
	argsYaml := argLines(q.Get("args"), "    ")
	envYaml := kvLines(q.Get("env"), "    ")

	// Description attrs
	idAttrsYaml := kvLines(q.Get("id_attrs"), "      ")
	nonIdAttrsYaml := kvLines(q.Get("non_id_attrs"), "      ")

	// Build optional YAML blocks
	opampPortLine := ""
	if opampPort != "" {
		opampPortLine = "  opamp_server_port: " + opampPort
	}
	argsBlock := ""
	if argsYaml != "" {
		argsBlock = "  args:\n" + argsYaml
	}
	envBlock := ""
	if envYaml != "" {
		envBlock = "  env:\n" + envYaml
	}
	accessBlock := ""
	if q.Get("read_allow") != "" || q.Get("read_deny") != "" || q.Get("write_allow") != "" {
		accessBlock = "  access_dirs:\n    read:\n      allow: " + readAllow + "\n      deny: " + readDeny + "\n    write:\n      allow: " + writeAllow
	}
	idBlock := ""
	if idAttrsYaml != "" {
		idBlock = "    identifying_attributes:\n" + idAttrsYaml
	}
	nonIdBlock := "    non_identifying_attributes:\n      agent.label: \"" + label + "\""
	if nonIdAttrsYaml != "" {
		nonIdBlock += "\n" + nonIdAttrsYaml
	}

	supervisorYAML := `server:
  endpoint: ` + endpoint + `

capabilities:
  accepts_remote_config: ` + capRemoteCfg + `
  accepts_restart_command: ` + capRestart + `
  accepts_opamp_connection_settings: ` + capOpampConn + `
  reports_effective_config: ` + capEffCfg + `
  reports_own_metrics: ` + capOwnMetrics + `
  reports_own_logs: ` + capOwnLogs + `
  reports_own_traces: ` + capOwnTraces + `
  reports_health: ` + capHealth + `
  reports_remote_config: ` + capRemoteSt + `
  reports_available_components: ` + capComponents + `
  reports_heartbeat: ` + capHeartbeat + `

storage:
  directory: ` + storageDir + `

agent:
  executable: ` + executable + `
  orphan_detection_interval: ` + orphanInterval + `
  bootstrap_timeout: ` + bootstrapTimeout + `
` + opampPortLine + `
  config_files:
    - $OWN_TELEMETRY_CONFIG
    - $OPAMP_EXTENSION_CONFIG
    - $REMOTE_CONFIG
` + argsBlock + `
` + envBlock + `
` + accessBlock + `
  description:
` + idBlock + `
` + nonIdBlock + `

telemetry:
  logs:
    level: ` + logLevel + `
    output_paths:
      - stderr
  metrics:
    level: ` + metricsLevel

	// Derive install paths from the executable param so the script matches
	// exactly what the user configured — no hardcoded paths.
	binDir := filepath.Dir(executable) // e.g. /opt/otelcol/bin
	installDir := filepath.Dir(binDir) // e.g. /opt/otelcol
	confDir := q.Get("conf_dir")
	if confDir == "" {
		confDir = "/etc/otel-supervisor"
	}
	serviceName := q.Get("service_name")
	if serviceName == "" {
		serviceName = "otel-supervisor"
	}

	script := renderScript(installScriptTemplate, map[string]string{
		"{{ENDPOINT}}":           endpoint,
		"{{OTEL_VERSION}}":       otelVer,
		"{{SUPERVISOR_VERSION}}": supVer,
		"{{LABEL}}":              label,
		"{{SUPERVISOR_YAML}}":    supervisorYAML,
		"{{INSTALL_DIR}}":        installDir,
		"{{BIN_DIR}}":            binDir,
		"{{CONF_DIR}}":           confDir,
		"{{STORAGE_DIR}}":        storageDir,
		"{{OTEL_USER}}":          runAs,
		"{{SERVICE_NAME}}":       serviceName,
	})

	if q.Get("download") == "1" {
		w.Header().Set("Content-Disposition", `attachment; filename="openfleet-install.sh"`)
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Write([]byte(script))
}

func (srv *server) handleUninstallScriptAPI(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	q := r.URL.Query()
	uid := sanitizeUID(q.Get("uid"))
	if uid == "" {
		http.Error(w, "Missing or invalid 'uid' query parameter", http.StatusBadRequest)
		return
	}

	// Mirror the same path params used at install time so cleanup is exact.
	executable := q.Get("executable")
	if executable == "" {
		executable = "/opt/otelcol/bin/otelcol-contrib"
	}
	binDir := filepath.Dir(executable)
	installDir := filepath.Dir(binDir)
	confDir := q.Get("conf_dir")
	if confDir == "" {
		confDir = "/etc/otel-supervisor"
	}
	storageDir := q.Get("storage_dir")
	if storageDir == "" {
		storageDir = "/var/lib/otelcol/supervisor"
	}
	runAs := q.Get("run_as")
	if runAs == "" {
		runAs = "otelcol"
	}
	serviceName := q.Get("service_name")
	if serviceName == "" {
		serviceName = "otel-supervisor"
	}

	// Derive the HTTP server URL from the incoming request so the script can
	// call back to delete the agent from the DB — no extra param needed.
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	openfleetURL := scheme + "://" + r.Host

	script := renderScript(uninstallScriptTemplate, map[string]string{
		"{{UID}}":           uid,
		"{{SERVICE_NAME}}":  serviceName,
		"{{INSTALL_DIR}}":   installDir,
		"{{BIN_DIR}}":       binDir,
		"{{CONF_DIR}}":      confDir,
		"{{STORAGE_DIR}}":   storageDir,
		"{{OTEL_USER}}":     runAs,
		"{{OPENFLEET_URL}}": openfleetURL,
	})

	if q.Get("download") == "1" {
		w.Header().Set("Content-Disposition", `attachment; filename="openfleet-uninstall.sh"`)
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Write([]byte(script))
}
